format_version: 10
pipelines:
  ci-pipeline:
    group: sample
    materials:
      app-repo:
        git: https://github.com/vishwajittripathi/gocd-lab.git
        branch: main
    stages:
      - build:
          clean_workspace: true
          jobs:
            build-job:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "=== BUILD ==="
                        python app.py
                        echo "Build success"
      - test:
          clean_workspace: false
          jobs:
            test-job:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "=== TEST ==="
                        pytest || echo "No tests"
      - deploy:
          approval:
            type: manual
          jobs:
            deploy-job:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "=== DEPLOY STAGE ==="
                        echo "Deploying app..."
                        sleep 3
                        echo "Deployed successfully."
